PUT http://localhost:3002/api/students/4809dbf3-df47-4189-be0e-72b3e28ca586
Content-Type: application/json

{
    "nombre": "Luisito test",
    "apellido": "prueba ramirez",
    "direccion": "calle 21 #33 c 11"
}